name: assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.7.0
  image_picker: ^1.1.2
  location: ^7.0.0
  omni_datetime_picker: ^2.0.3
  provider: ^6.1.2
  file_picker: ^5.2.2
  table_calendar: ^3.0.7
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Bold.ttf
        - asset: assets/fonts/Fredoka-Light.ttf
        - asset: assets/fonts/Fredoka-Medium.ttf
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-SemiBold.ttf
  assets:
    - assets/images/logo.png
    - assets/images/profile_placeholder.jpeg
  uses-material-design: true
